version: "3"
services:
  mongodb:
    image: mongo
  app:
    build: ./
    depends_on:
      - mongodb
    ports:
      - 4711:9090
    command: ["/usr/local/bin/dockerize" ,"-wait","tcp://mongodb:27017","/usr/local/bin/gridfileserv","mongodb","-url","mongodb:27017"]